### ISSUE TITLE
Discuss about logistics plans

### ISSUE THREAD

**Issue by ankur198** [VueFireCommerce/Logistics-App#1]
Are we going to use some third party logistics like [iThinkLogistics](https://www.ithinklogistics.com/), [shiprocket](https://www.shiprocket.in/pricing/), etc

### or

we will have have our own team for delivery?

**Comment by pawasj** [comment]
Yes, mostly Shiprocket.

**Comment by ankur198** [comment]
Okk so the our part of logistics will keep up inventory details and integration to shiprocket

**Comment by pawasj** [comment]
Yes
